!obj:pylearn2.train.Train {
    dataset: &train !obj:DNNSMM.datasets.kaldi_timit.TIMIT {
        which_set: 'train',
        start: 0,
        stop: 10000,
        framesize: &fs 11
    },
    model: !obj:pylearn2.models.mlp.MLP {
        layers: [ !obj:pylearn2.models.mlp.RectifiedLinear {
                     layer_name: 'h0',
                     dim: &dim 300,
                     irange: .05,
                     max_col_norm: 1.9365,
                 }, !obj:pylearn2.models.mlp.RectifiedLinear {
                     layer_name: 'h1',
                     dim: *dim,
                     irange: .05,
                     max_col_norm: 1.9365,
                 }, !obj:pylearn2.models.mlp.RectifiedLinear {
                     layer_name: 'h2',
                     dim: *dim,
                     irange: .05,
                     max_col_norm: 1.9365,
                 }, !obj:pylearn2.models.mlp.Softmax {
                     layer_name: 'y',
                     n_classes: 144,
                     irange: 0.
                 }
                ],
        nvis: 440,
    },
    algorithm: !obj:pylearn2.training_algorithms.sgd.SGD {
        batch_size: 100,
        learning_rate: .000001,
        monitoring_dataset: {
                'train' : *train,
                'valid' : !obj:DNNSMM.datasets.kaldi_timit.TIMIT {
                              which_set: 'train',
                              start: 10001,
                              stop: 11000,
                              framesize: *fs
                          },
                'test'  : !obj:DNNSMM.datasets.kaldi_timit.TIMIT {
                              which_set: 'train',
                              start: 11001,
                              stop: 12000,
                              framesize: *fs
                          }
        },
        cost: !obj:pylearn2.costs.cost.SumOfCosts { costs: [
            !obj:pylearn2.costs.mlp.Default {
            }, !obj:pylearn2.costs.mlp.WeightDecay {
                coeffs: [ .00005, .00005, .00005, .00005]
            }, !obj:pylearn2.costs.mlp.dropout.Dropout {
                input_include_probs: { h0: 0.5, h1: 0.5}
            }
            ]
        },
        learning_rule: !obj:pylearn2.training_algorithms.learning_rule.AdaDelta {
        },
        termination_criterion: !obj:pylearn2.termination_criteria.EpochCounter {
                    max_epochs: 100
                }
    },
    save_freq: 1,
    save_path: 'result/kaldi_test.pkl'
}
